### ISSUE TITLE
bulk time entries occured 500 error

### ISSUE THREAD

**Issue by archonwang** [upgradeya/redmine-contracts-with-time-tracking-plugin#52]
@upgradeya, 
error log as follows ,please check it. Thanks.

```
A NoMethodError occurred in contracts#add_time_entries:
 
  undefined method `sort_by!' for #<ActiveRecord::Associations::CollectionProxy []>
  plugins/contracts/app/controllers/contracts_controller.rb:175:in `add_time_entries'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/projects/uth_rdc/contracts/2/add_time_entries
  * HTTP Method: GET
  * IP address : 192.168.60.238
  * Parameters : {"controller"=>"contracts", "action"=>"add_time_entries", "project_id"=>"uth_rdc", "id"=>"2"}
  * Timestamp  : 2017-02-14 13:25:38 UTC
  * Server : jira
  * Rails root : /opt/redmine-3.3
  * Process: 1529
 
-------------------------------
Session:
-------------------------------
 
  * session id: "f9ef347bbf440e97098637187098880d"
  * data: {"session_id"=>"f9ef347bbf440e97098637187098880d",
   "user_id"=>"8",
   "tk"=>"d66fcd7c46bdcc0c2deb09849a16565cc7348d9d",
   "sudo_timestamp"=>1487048639,
   "my_page_sort"=>"none",
   "_csrf_token"=>"iMJZfondjGlwdKY3bXNqX+rJ0jwt/fjGexLnbeK7YJc=",
   "recent_projects"=>[34, 1, 5],
   "wktimes"=>
    {:period_type=>nil,
     :period=>nil,
     :from=>nil,
     :to=>nil,
     :project_id=>nil,
     :filter_type=>nil,
     :user_id=>nil,
     :status=>nil,
     :group_id=>nil,
     :filters=>nil},
   "wkexpense"=>
    {:period_type=>nil,
     :period=>nil,
     :from=>nil,
     :to=>nil,
     :project_id=>nil,
     :filter_type=>nil,
     :user_id=>nil,
     :status=>nil,
     :group_id=>nil,
     :filters=>nil},
   "wkinvoice"=>
    {:period_type=>nil,
     :period=>nil,
     :account_id=>nil,
     :project_id=>nil,
     :from=>nil,
     :to=>nil},
   "contract"=>{:account_id=>nil, :project_id=>nil},
   "wkopportunity"=>
    {:period_type=>nil,
     :period=>nil,
     :from=>nil,
     :to=>nil,
     :oppname=>nil,
     :account_id=>nil},
   "wkcrmcontact"=>{:contactname=>nil, :account_id=>nil},
   "accountproject"=>{:account_id=>nil, :project_id=>nil},
   "wkgltransaction"=>
    {:period_type=>nil, :period=>nil, :ledger_id=>nil, :from=>nil, :to=>nil},
   "wkledger"=>{:ledger_type=>nil, :name=>nil},
   "wkreport"=>
    {:report_type=>nil,
     :period_type=>nil,
     :period=>nil,
     :group_id=>nil,
     :user_id=>nil,
     :from=>Wed, 01 Feb 2017,
     :to=>Tue, 28 Feb 2017},
   "query"=>
    {:project_id=>34,
     :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
     :group_by=>"parent",
     :column_names=>nil,
     :totalable_names=>[:estimated_hours]},
   "issues_index_sort"=>"id:desc",
   "show_locked_contracts"=>true,
   "spectator_id"=>1,
   "my_account_sort"=>"none"}
 
-------------------------------
Environment:
-------------------------------
 
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _redmine_session=ckRwU0JCWmU3ZDBMYXNIanR5NFd4cUpBR3hDOVlpZU0yYVZJVjdsc3UvMGovVklWOFFNZXBtWFpKNklncktrcmxBMHRjYUpydFU4SThHc0ZYd2dTQzc3WnNtazBMTlhHUlJScFJmYS9uQS9uT2huZWxCNTVGUjlqd1ZYOGtleGdJb0hMNnAxa29RUjhsUzVTWWxLWnpQbmZrZnpoOWwwRi93Q2p4S2REalJOMmhvT0g3dmVoRjNtY3UvZTdFeUtvUnpYL3o3N0Y2S09NUWJjanZBdVpVWE9SUDBYeUpoMUZYOXVtMzV1dXFGcVRhSklVb0dYVVNyZW9ORzJuM2MyVU5wbGx6VlZRMjdDdCtpTzBWeDdoTjFHMUJDM08ySjNoRklrRFV0WkdaMTVWcDRHbjViZWV4YnZ2WE93UmdpdFpIZjZGUWdFOHFTUmlidmJKU040eFV0WG5tUmVvdE1EcjZkMTh1TjlzUVdtRXlyVUI2YmJiU3Q5MVVwMnZoa1UwZGdlZkZWTFRZelRQa0Zvd0hockxjdml3MkdvVmdVWFUvOXZjVW9kTmFlRVNCYXpDZWJLaVRqOWQ4MnFkWkJuRjBaNmI0dHdqVVlFaytEZGhNSTh1NEQwQUVjUXFzTEljT210aWtoV25pREVjZWZ4MEh3aS96OHdlL1hvT2VkTWFsOFpsK0t3YlZzclQ5cndybVg4Y2JCRFZ0UzkyVDR5N2w2RkV2YnY5djlVRnFYbnVDcFRPRnlNZGdFMi83Zkk4a2Viak92Ynk2dDRzckNVNDZHZ3RZbGJrdFh4VzNKakhaRzVJSURpT09TYTBoMEE4bGpQaWdXL21meVBHakV0dnMwak9pWDhhZVV5endCZDVudUczVloybXJ3bktJYWRBQi9JS1pIRTZiYXd5MFdkelpTR3Z5aThjOGFaR3lMd3hWckFzbHg4eG5iZ2oreWxPUGhQUk5EdU5IdkVnbzlzK0JNZHpXdWQ3OG5NKytlejdpVUpNdGV3YkJrTlBPVllaR05zREhqUWdrVEszSHJUQ0xPaFFzZm5aZ282aWFaOCtOUVdvMGRsVUkrM3VSbE5JVmVkMTVocFFXNlBmaGFnSER1ZDg0cTV4QUhFRzNEbTlYTjE3WVpMcXBCVkh0RDVkZTlFd3FUeXQ0WUphekRMSTdIaXN4cEY2cHZQNXBXM1AzVEF2U0RzWGR6Q3lIK0JLRXJRSHBtWkpzZ2NmSk1Kb1RMN2N5aVFYRmE5SVFEOGJXVkJITnJVeXJhN2toMGF3ZUI3aWxrd050RFBRY2orV1VzdVc4TFY3WmFUK01JaUdPSzRVM0lKSnFJUGlrb2RNb1hpWjZXaFNNNHltQWZKdFA4b1BiNk01VVNIQ2tsaUJHQnhVdzFkSllaeU5wTDVMTis2bVVuMmlVcExCSUZPc0ViVGdRSUxvUlFuTjJJWkJXUEhOQ3B5UUl6ODByYTZuRm5nMWNXaWRjSjk5LzN0c0ZaSDNlUmlqU2FuK0lYZmxXeVZNNHBXOVJ6YUxIVTFiMHRWQWp5SWlJbzRDU3Nha2p3U0NtMVdGL251TEJaSjRxQnZCcFloUDhoOGVyNW5HendDNFdRbHkvSXR6L0Rtb0QvOEJ6ZHJYdzZKR1k2SURNbjJMVWNyQ1hTcTlBZlJNb3ZoNEcvOHFCZjlmdkxxNWNMUllFTEsvSklVMVE4dWErczYwcTliSUsxNXJ5NmMvL1lTZFRqQ3Uvd2JpcXdoWXVyUHFBUlAzMUxRWjZ2TC80RU1mZHVpOWEybEtMbWhBV1E5WXRGUW1pYzNranhHUnVka0MvSTdUOWN3QkpWZm5tNTZ5c3B2UTZobkdKOWRadGpQRHhGSHpuVk9CME51WlpTNWJzc3cveXRJelJkTG5IN1FRYzNSY2tMb242RUZnOXYwY1JhUjAyRUFUbGUrYlNVckdzdmh1TTlGRlBLeWotLWZIVEFKdHdkNU05ZEl3VXZhV1VUQVE9PQ%3D%3D--5b14e4e9b323c5d2f88d38c10838b015fd4a43d8
  * HTTP_HOST                                      : 192.168.1.41
* HTTP_REFERER : http://192.168.1.41/projects/uth_rdc/contracts/2/add_time_entries
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : /projects/uth_rdc/contracts/2/add_time_entries
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /projects/uth_rdc/contracts/2/add_time_entries
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 192.168.60.238
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /projects/uth_rdc/contracts/2/add_time_entries
  * REQUEST_URI                                    : /projects/uth_rdc/contracts/2/add_time_entries
  * ROUTES_45551000_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<ContractsController:0x007f42ed358d88>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000005742160>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f42ed3060d8>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000000c49d6d8>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000000577a5d8>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 192.168.60.238
  * action_dispatch.request.accepts                : [#<Mime::Type:0x007f42ed307398 @synonyms=[], @symbol=nil, @string="*/*", @hash=3339535301955937444>]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f42ed307398 @synonyms=[], @symbol=nil, @string="*/*", @hash=3339535301955937444>]
  * action_dispatch.request.parameters             : {"controller"=>"contracts", "action"=>"add_time_entries", "project_id"=>"uth_rdc", "id"=>"2"}
  * action_dispatch.request.path_parameters        : {:controller=>"contracts", :action=>"add_time_entries", :project_id=>"uth_rdc", :id=>"2"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"f9ef347bbf440e97098637187098880d", "user_id"=>"8", "tk"=>"d66fcd7c46bdcc0c2deb09849a16565cc7348d9d", "sudo_timestamp"=>1487048639, "my_page_sort"=>"none", "_csrf_token"=>"iMJZfondjGlwdKY3bXNqX+rJ0jwt/fjGexLnbeK7YJc=", "recent_projects"=>[34, 1, 5], "wktimes"=>{:period_type=>nil, :period=>nil, :from=>nil, :to=>nil, :project_id=>nil, :filter_type=>nil, :user_id=>nil, :status=>nil, :group_id=>nil, :filters=>nil}, "wkexpense"=>{:period_type=>nil, :period=>nil, :from=>nil, :to=>nil, :project_id=>nil, :filter_type=>nil, :user_id=>nil, :status=>nil, :group_id=>nil, :filters=>nil}, "wkinvoice"=>{:period_type=>nil, :period=>nil, :account_id=>nil, :project_id=>nil, :from=>nil, :to=>nil}, "contract"=>{:account_id=>nil, :project_id=>nil}, "wkopportunity"=>{:period_type=>nil, :period=>nil, :from=>nil, :to=>nil, :oppname=>nil, :account_id=>nil}, "wkcrmcontact"=>{:contactname=>nil, :account_id=>nil}, "accountproject"=>{:account_id=>nil, :project_id=>nil}, "wkgltransaction"=>{:period_type=>nil, :period=>nil, :ledger_id=>nil, :from=>nil, :to=>nil}, "wkledger"=>{:ledger_type=>nil, :name=>nil}, "wkreport"=>{:report_type=>nil, :period_type=>nil, :period=>nil, :group_id=>nil, :user_id=>nil, :from=>Wed, 01 Feb 2017, :to=>Tue, 28 Feb 2017}, "query"=>{:project_id=>34, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>"parent", :column_names=>nil, :totalable_names=>[:estimated_hours]}, "issues_index_sort"=>"id:desc", "show_locked_contracts"=>true, "spectator_id"=>1, "my_account_sort"=>"none"}
  * action_dispatch.request_id                     : 2a4cdd77-72b5-49ae-b36f-e6d035ef9948
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000056e1b30>
  * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x007f42ed3a9a58>
  * rack.errors                                    : #<IO:0x00000002025588>
  * rack.input                                     : #<StringIO:0x007f42ed3aa610>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_redmine_session"=>"ckRwU0JCWmU3ZDBMYXNIanR5NFd4cUpBR3hDOVlpZU0yYVZJVjdsc3UvMGovVklWOFFNZXBtWFpKNklncktrcmxBMHRjYUpydFU4SThHc0ZYd2dTQzc3WnNtazBMTlhHUlJScFJmYS9uQS9uT2huZWxCNTVGUjlqd1ZYOGtleGdJb0hMNnAxa29RUjhsUzVTWWxLWnpQbmZrZnpoOWwwRi93Q2p4S2REalJOMmhvT0g3dmVoRjNtY3UvZTdFeUtvUnpYL3o3N0Y2S09NUWJjanZBdVpVWE9SUDBYeUpoMUZYOXVtMzV1dXFGcVRhSklVb0dYVVNyZW9ORzJuM2MyVU5wbGx6VlZRMjdDdCtpTzBWeDdoTjFHMUJDM08ySjNoRklrRFV0WkdaMTVWcDRHbjViZWV4YnZ2WE93UmdpdFpIZjZGUWdFOHFTUmlidmJKU040eFV0WG5tUmVvdE1EcjZkMTh1TjlzUVdtRXlyVUI2YmJiU3Q5MVVwMnZoa1UwZGdlZkZWTFRZelRQa0Zvd0hockxjdml3MkdvVmdVWFUvOXZjVW9kTmFlRVNCYXpDZWJLaVRqOWQ4MnFkWkJuRjBaNmI0dHdqVVlFaytEZGhNSTh1NEQwQUVjUXFzTEljT210aWtoV25pREVjZWZ4MEh3aS96OHdlL1hvT2VkTWFsOFpsK0t3YlZzclQ5cndybVg4Y2JCRFZ0UzkyVDR5N2w2RkV2YnY5djlVRnFYbnVDcFRPRnlNZGdFMi83Zkk4a2Viak92Ynk2dDRzckNVNDZHZ3RZbGJrdFh4VzNKakhaRzVJSURpT09TYTBoMEE4bGpQaWdXL21meVBHakV0dnMwak9pWDhhZVV5endCZDVudUczVloybXJ3bktJYWRBQi9JS1pIRTZiYXd5MFdkelpTR3Z5aThjOGFaR3lMd3hWckFzbHg4eG5iZ2oreWxPUGhQUk5EdU5IdkVnbzlzK0JNZHpXdWQ3OG5NKytlejdpVUpNdGV3YkJrTlBPVllaR05zREhqUWdrVEszSHJUQ0xPaFFzZm5aZ282aWFaOCtOUVdvMGRsVUkrM3VSbE5JVmVkMTVocFFXNlBmaGFnSER1ZDg0cTV4QUhFRzNEbTlYTjE3WVpMcXBCVkh0RDVkZTlFd3FUeXQ0WUphekRMSTdIaXN4cEY2cHZQNXBXM1AzVEF2U0RzWGR6Q3lIK0JLRXJRSHBtWkpzZ2NmSk1Kb1RMN2N5aVFYRmE5SVFEOGJXVkJITnJVeXJhN2toMGF3ZUI3aWxrd050RFBRY2orV1VzdVc4TFY3WmFUK01JaUdPSzRVM0lKSnFJUGlrb2RNb1hpWjZXaFNNNHltQWZKdFA4b1BiNk01VVNIQ2tsaUJHQnhVdzFkSllaeU5wTDVMTis2bVVuMmlVcExCSUZPc0ViVGdRSUxvUlFuTjJJWkJXUEhOQ3B5UUl6ODByYTZuRm5nMWNXaWRjSjk5LzN0c0ZaSDNlUmlqU2FuK0lYZmxXeVZNNHBXOVJ6YUxIVTFiMHRWQWp5SWlJbzRDU3Nha2p3U0NtMVdGL251TEJaSjRxQnZCcFloUDhoOGVyNW5HendDNFdRbHkvSXR6L0Rtb0QvOEJ6ZHJYdzZKR1k2SURNbjJMVWNyQ1hTcTlBZlJNb3ZoNEcvOHFCZjlmdkxxNWNMUllFTEsvSklVMVE4dWErczYwcTliSUsxNXJ5NmMvL1lTZFRqQ3Uvd2JpcXdoWXVyUHFBUlAzMUxRWjZ2TC80RU1mZHVpOWEybEtMbWhBV1E5WXRGUW1pYzNranhHUnVka0MvSTdUOWN3QkpWZm5tNTZ5c3B2UTZobkdKOWRadGpQRHhGSHpuVk9CME51WlpTNWJzc3cveXRJelJkTG5IN1FRYzNSY2tMb242RUZnOXYwY1JhUjAyRUFUbGUrYlNVckdzdmh1TTlGRlBLeWotLWZIVEFKdHdkNU05ZEl3VXZhV1VUQVE9PQ==--5b14e4e9b323c5d2f88d38c10838b015fd4a43d8"}
  * rack.request.cookie_string                     : _redmine_session=ckRwU0JCWmU3ZDBMYXNIanR5NFd4cUpBR3hDOVlpZU0yYVZJVjdsc3UvMGovVklWOFFNZXBtWFpKNklncktrcmxBMHRjYUpydFU4SThHc0ZYd2dTQzc3WnNtazBMTlhHUlJScFJmYS9uQS9uT2huZWxCNTVGUjlqd1ZYOGtleGdJb0hMNnAxa29RUjhsUzVTWWxLWnpQbmZrZnpoOWwwRi93Q2p4S2REalJOMmhvT0g3dmVoRjNtY3UvZTdFeUtvUnpYL3o3N0Y2S09NUWJjanZBdVpVWE9SUDBYeUpoMUZYOXVtMzV1dXFGcVRhSklVb0dYVVNyZW9ORzJuM2MyVU5wbGx6VlZRMjdDdCtpTzBWeDdoTjFHMUJDM08ySjNoRklrRFV0WkdaMTVWcDRHbjViZWV4YnZ2WE93UmdpdFpIZjZGUWdFOHFTUmlidmJKU040eFV0WG5tUmVvdE1EcjZkMTh1TjlzUVdtRXlyVUI2YmJiU3Q5MVVwMnZoa1UwZGdlZkZWTFRZelRQa0Zvd0hockxjdml3MkdvVmdVWFUvOXZjVW9kTmFlRVNCYXpDZWJLaVRqOWQ4MnFkWkJuRjBaNmI0dHdqVVlFaytEZGhNSTh1NEQwQUVjUXFzTEljT210aWtoV25pREVjZWZ4MEh3aS96OHdlL1hvT2VkTWFsOFpsK0t3YlZzclQ5cndybVg4Y2JCRFZ0UzkyVDR5N2w2RkV2YnY5djlVRnFYbnVDcFRPRnlNZGdFMi83Zkk4a2Viak92Ynk2dDRzckNVNDZHZ3RZbGJrdFh4VzNKakhaRzVJSURpT09TYTBoMEE4bGpQaWdXL21meVBHakV0dnMwak9pWDhhZVV5endCZDVudUczVloybXJ3bktJYWRBQi9JS1pIRTZiYXd5MFdkelpTR3Z5aThjOGFaR3lMd3hWckFzbHg4eG5iZ2oreWxPUGhQUk5EdU5IdkVnbzlzK0JNZHpXdWQ3OG5NKytlejdpVUpNdGV3YkJrTlBPVllaR05zREhqUWdrVEszSHJUQ0xPaFFzZm5aZ282aWFaOCtOUVdvMGRsVUkrM3VSbE5JVmVkMTVocFFXNlBmaGFnSER1ZDg0cTV4QUhFRzNEbTlYTjE3WVpMcXBCVkh0RDVkZTlFd3FUeXQ0WUphekRMSTdIaXN4cEY2cHZQNXBXM1AzVEF2U0RzWGR6Q3lIK0JLRXJRSHBtWkpzZ2NmSk1Kb1RMN2N5aVFYRmE5SVFEOGJXVkJITnJVeXJhN2toMGF3ZUI3aWxrd050RFBRY2orV1VzdVc4TFY3WmFUK01JaUdPSzRVM0lKSnFJUGlrb2RNb1hpWjZXaFNNNHltQWZKdFA4b1BiNk01VVNIQ2tsaUJHQnhVdzFkSllaeU5wTDVMTis2bVVuMmlVcExCSUZPc0ViVGdRSUxvUlFuTjJJWkJXUEhOQ3B5UUl6ODByYTZuRm5nMWNXaWRjSjk5LzN0c0ZaSDNlUmlqU2FuK0lYZmxXeVZNNHBXOVJ6YUxIVTFiMHRWQWp5SWlJbzRDU3Nha2p3U0NtMVdGL251TEJaSjRxQnZCcFloUDhoOGVyNW5HendDNFdRbHkvSXR6L0Rtb0QvOEJ6ZHJYdzZKR1k2SURNbjJMVWNyQ1hTcTlBZlJNb3ZoNEcvOHFCZjlmdkxxNWNMUllFTEsvSklVMVE4dWErczYwcTliSUsxNXJ5NmMvL1lTZFRqQ3Uvd2JpcXdoWXVyUHFBUlAzMUxRWjZ2TC80RU1mZHVpOWEybEtMbWhBV1E5WXRGUW1pYzNranhHUnVka0MvSTdUOWN3QkpWZm5tNTZ5c3B2UTZobkdKOWRadGpQRHhGSHpuVk9CME51WlpTNWJzc3cveXRJelJkTG5IN1FRYzNSY2tMb242RUZnOXYwY1JhUjAyRUFUbGUrYlNVckdzdmh1TTlGRlBLeWotLWZIVEFKdHdkNU05ZEl3VXZhV1VUQVE9PQ%3D%3D--5b14e4e9b323c5d2f88d38c10838b015fd4a43d8
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f42ed35b268>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f42ed35b218>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/contracts/app/controllers/contracts_controller.rb:175:in `add_time_entries'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 
 
```

**Comment by wesoccer2003** [comment]
Hey Steven,

Thanks for submitting your issue. Bulk time entries have not been working for a while, so for now I have removed the button from the UI until we get some time to work on it.

**Comment by archonwang** [comment]
@wesoccer2003 
Thanks.
